FROM alpine:3.15.3
LABEL maintainer "David Perez Cabrera <dperezcabrera@gmail.com>"

RUN apk add --no-cache openjdk11 --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community
RUN apk add --no-cache docker

